### ISSUE TITLE
Unable to save settings: Failed to save settings. Please restart IntelliJ IDEA

### ISSUE THREAD

**Issue by pawdat** [HaxeFoundation/intellij-haxe#1077]
Plugin version: 1.3.1
IDEA version: 2020.3.2 Community Edition 
OS and OS version: Mac OS Catalina (10.15.7)
JDK version: none installed

Intellij logs are attached bellow. It looks like plugin is trying to create haxe.xml file in root file system which is read only even with sudo permissions.
```
2021-02-18 07:54:59,660 [150446870]   WARN - mponents.impl.stores.StoreUtil - Save settings failed 
java.io.IOException: Cannot create file '/haxe.xml'
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.createChildFile(LocalFileSystemBase.java:337)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.createChildFile(PersistentFSImpl.java:485)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.createChildData(VirtualFileSystemEntry.java:275)
	at com.intellij.configurationStore.StorageUtilKt.getOrCreateVirtualFile(storageUtil.kt:147)
	at com.intellij.configurationStore.FileBasedStorageKt.writeFile(FileBasedStorage.kt:269)
	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.saveLocally(FileBasedStorage.kt:115)
	at com.intellij.configurationStore.XmlElementStorage$XmlElementStorageSaveSession$SaveExecutor.save(XmlElementStorage.kt:164)
	at com.intellij.configurationStore.SaveExecutorKt.executeSave(SaveExecutor.kt:92)
	at com.intellij.configurationStore.SaveExecutorKt.saveSessions(SaveExecutor.kt:86)
	at com.intellij.configurationStore.ProjectSaveSessionProducerManager$saveWithAdditionalSaveSessions$$inlined$withEdtContext$1$lambda$1.compute(actions.kt:63)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$16(ApplicationImpl.java:1009)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:988)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
	at com.intellij.configurationStore.ProjectSaveSessionProducerManager$saveWithAdditionalSaveSessions$$inlined$withEdtContext$1.invokeSuspend(ComponentStoreImpl.kt:709)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion$scheduleWithinConstraints$1.invoke(BaseConstrainedExecution.kt:68)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion.scheduleWithinConstraints(BaseConstrainedExecution.kt:71)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution.scheduleWithinConstraints(BaseConstrainedExecution.kt:38)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl.access$scheduleWithinConstraints$s1153900543(BaseExpirableExecutorMixinImpl.kt:12)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl$scheduleWithinConstraints$$inlined$Runnable$1.run(Runnable.kt:19)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-02-18 07:55:28,198 [150475408]   INFO - rationStore.ComponentStoreImpl - Saving appLafManager took 18 ms 
2021-02-18 07:55:28,201 [150475411]   INFO - lij.openapi.util.io.FileUtilRt - /haxe.xml (Read-only file system) 
java.io.FileNotFoundException: /haxe.xml (Read-only file system)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at com.intellij.openapi.util.io.FileUtilRt.createIfNotExists(FileUtilRt.java:1025)
	at com.intellij.openapi.util.io.FileUtil.createIfDoesntExist(FileUtil.java:380)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.createChildFile(LocalFileSystemBase.java:336)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.createChildFile(PersistentFSImpl.java:485)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.createChildData(VirtualFileSystemEntry.java:275)
	at com.intellij.configurationStore.StorageUtilKt.getOrCreateVirtualFile(storageUtil.kt:147)
	at com.intellij.configurationStore.FileBasedStorageKt.writeFile(FileBasedStorage.kt:269)
	at com.intellij.configurationStore.FileBasedStorage$FileSaveSession.saveLocally(FileBasedStorage.kt:115)
	at com.intellij.configurationStore.XmlElementStorage$XmlElementStorageSaveSession$SaveExecutor.save(XmlElementStorage.kt:164)
	at com.intellij.configurationStore.SaveExecutorKt.executeSave(SaveExecutor.kt:92)
	at com.intellij.configurationStore.SaveExecutorKt.saveSessions(SaveExecutor.kt:86)
	at com.intellij.configurationStore.ProjectSaveSessionProducerManager$saveWithAdditionalSaveSessions$$inlined$withEdtContext$1$lambda$1.compute(actions.kt:63)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$16(ApplicationImpl.java:1009)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:988)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1009)
	at com.intellij.configurationStore.ProjectSaveSessionProducerManager$saveWithAdditionalSaveSessions$$inlined$withEdtContext$1.invokeSuspend(ComponentStoreImpl.kt:709)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion$scheduleWithinConstraints$1.invoke(BaseConstrainedExecution.kt:68)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion.scheduleWithinConstraints(BaseConstrainedExecution.kt:71)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution.scheduleWithinConstraints(BaseConstrainedExecution.kt:38)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl.access$scheduleWithinConstraints$s1153900543(BaseExpirableExecutorMixinImpl.kt:12)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl$scheduleWithinConstraints$$inlined$Runnable$1.run(Runnable.kt:19)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by Beckwahn** [comment]
Same here. 
Plugin V. 1.3.1, CE 2020.3, Mac OS Big Sur 11.2.1, no JDK

In the IDE all imports are greyed out and repeatedly appearing Errors in the event log and notification:
_"12:30	Unable to save settings: Failed to save settings. Please restart IntelliJ IDEA"_

Also got the following entries in the log file:

`2021-02-18 12:04:48,167 [ 129229]   INFO - lij.openapi.util.io.FileUtilRt - /haxe.xml (Read-only file system) 
java.io.FileNotFoundException: /haxe.xml (Read-only file system)`

`2021-02-18 12:04:48,168 [ 129230]   WARN - mponents.impl.stores.StoreUtil - Save settings failed 
java.io.IOException: Cannot create file '/haxe.xml'`

`2021-02-18 12:05:16,106 [ 157168]   WARN - tions.ex.ConfigurableCardPanel - auto-dispose 'Plugins' id=preferences.pluginManager 
2021-02-18 12:05:16,423 [ 157485]   INFO - lij.openapi.util.io.FileUtilRt - /haxe.xml (Read-only file system) 
java.io.FileNotFoundException: /haxe.xml (Read-only file system)`

`2021-02-18 12:05:16,424 [ 157486]   WARN - mponents.impl.stores.StoreUtil - Save settings failed 
java.io.IOException: Cannot create file '/haxe.xml'`

`2021-02-18 12:05:22,167 [ 163229]   INFO - lij.openapi.util.io.FileUtilRt - /haxe.xml (Read-only file system) 
java.io.FileNotFoundException: /haxe.xml (Read-only file system)`

... and so on…

**Comment by m0rkeulv** [comment]
my best guess here is that `file`  in the  storage annotation for our module type is removed now. its been deprecated and probably removed in 2020.3 and newer.

possible fix:
 replace the followinf in `HaxeModuleSettings`
```
 @Storage(
      file = "$MODULE_FILE$"
    )
```
with this.
```
 @Storage(
      value = "$MODULE_FILE$"
    )
```

**Comment by trnzk** [comment]
In the HaxeProjectSettings file, changing ```@Storage("/haxe.xml") ```  to ```@Storage("haxe.xml")``` fixes the exception. However, I do not know if this is the right solution.

**Comment by EricBishton** [comment]
It looks more like the implied relative position of the file has changed to an absolute position.  Yes, there is a change between `file =` and `value =`, but the shorthand version should be acceptable in both cases, and that is what we use.  So, my thinking is that HaxeProjectSettings should be using `@Storage("haxe.xml")` as @trnzk has tried.  But we need just a bit more information.

@trnzk With the change of removing the leading `/` from the file name, did the haxe.xml file end up in the projects' `.idea` directory?  

If so, then that is the proper change.  If not, then we probably need a hybrid like `@Storage("$MODULE_FILE$/haxe.xml")`.

**Comment by trnzk** [comment]
@EricBishton, yes, the projects' .idea directory contains the haxe.xml file. Also, when I change the project macros in the haxe settings, the haxe.xml file in the .idea directory is updated accordingly.

**Comment by EricBishton** [comment]
@trnzk   Sweet.  Since you've figured it out, would you like to make a PR?

**Comment by Beckwahn** [comment]
Thank you guys! Just made a fresh build with your fixes and it works like a charm (imports too)! :)

**Comment by EricBishton** [comment]
Will be in release 1.4.
