### ISSUE TITLE
[Resolved] UnsupportedClassVersionError

### ISSUE THREAD

**Issue by barisyild** [HaxeFoundation/intellij-haxe#1124]
```ex
Internal error (java.lang.UnsupportedClassVersionError): org/jetbrains/jps/haxe/model/impl/JpsHaxeModelSerializerExtension has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
java.lang.UnsupportedClassVersionError: org/jetbrains/jps/haxe/model/impl/JpsHaxeModelSerializerExtension has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:512)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:420)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:414)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:413)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1209)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1383)
	at com.intellij.util.containers.ContainerUtil.newArrayList(ContainerUtil.java:151)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl$SingleClassLoaderPluginManager.loadExtensions(JpsServiceManagerImpl.java:113)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.loadExtensions(JpsServiceManagerImpl.java:105)
	at org.jetbrains.jps.service.impl.JpsServiceManagerImpl.getExtensions(JpsServiceManagerImpl.java:58)
	at org.jetbrains.jps.model.serialization.JpsModelSerializerExtension.getExtensions(JpsModelSerializerExtension.java:47)
	at org.jetbrains.jps.model.serialization.library.JpsSdkTableSerializer.getSdkPropertiesSerializer(JpsSdkTableSerializer.java:132)
	at org.jetbrains.jps.model.serialization.library.JpsSdkTableSerializer.loadSdk(JpsSdkTableSerializer.java:67)
	at org.jetbrains.jps.model.serialization.library.JpsSdkTableSerializer.loadSdks(JpsSdkTableSerializer.java:59)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader$SdkTableSerializer.loadExtension(JpsGlobalLoader.java:117)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader$SdkTableSerializer.loadExtension(JpsGlobalLoader.java:110)
	at org.jetbrains.jps.model.serialization.JpsLoaderBase.loadComponents(JpsLoaderBase.java:45)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.loadGlobalComponents(JpsGlobalLoader.java:73)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.load(JpsGlobalLoader.java:63)
	at org.jetbrains.jps.model.serialization.JpsGlobalLoader.loadGlobalSettings(JpsGlobalLoader.java:45)
	at org.jetbrains.jps.model.serialization.impl.JpsSerializationManagerImpl.loadModel(JpsSerializationManagerImpl.java:20)
	at org.jetbrains.jps.cmdline.JpsModelLoaderImpl.loadModel(JpsModelLoaderImpl.java:34)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:68)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:365)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:214)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:211)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

Intellij Idea 2023.1.3
Windows 11
Build: 1.4.3 beta 2 build (d8e420c0)
To reproduce: Build openfl project

### Solution from @m0rkeulv: 

> as far as i can tell, you have either default java version is not 17, or you have set a java SDK in project settings that is below 17. (if you set a java JDK in project settings it will use that when it tries to create the build process and if its below java 17 it will fail as it cant read the class files)
> 
> i can see if i can compile the Jps project with a lower version in my next build (not sure if its possible as it is using the commons module as well)

**Comment by m0rkeulv** [comment]
you need java 17 JDK (from the error message it seems you have java 16 installed)

**Comment by barisyild** [comment]
> you need java 17 JDK (from the error message it seems you have java 16 installed)

I'm not trying to compile, I'm already using the current beta build.

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/8f1de33a-a489-454d-8e94-63b91aefff2b)

Intellij Java Path (For Windows): ...\IDEA-U\ch-0\231.9161.38\jbr\bin\java.exe

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/d89474fd-3113-4c25-b83a-660ed848a6a3)

**Comment by m0rkeulv** [comment]
as far as i can tell, you have either default java version is not 17, or you have set a java SDK in project settings that is below 17.
(if you set a java JDK in project settings it will use that when it tries to create the build process and if its below java 17 it will fail as it cant read the class files)

i can see if i can compile the  Jps project with a lower version in my next build (not sure if its possible as it is using the commons module as well)

**Comment by EricBishton** [comment]
From https://en.wikipedia.org/wiki/Java_class_file#General_layout:

major version number of the class file format being used.[[3]](https://en.wikipedia.org/wiki/Java_class_file#cite_note-3)
Java SE 21 = 65 (0x41 hex),
Java SE 20 = 64 (0x40 hex),
Java SE 19 = 63 (0x3F hex),
Java SE 18 = 62 (0x3E hex),
Java SE 17 = 61 (0x3D hex),     <<<<<<--------  @barisyild, This is what is being complained about.
Java SE 16 = 60 (0x3C hex),    <<< --- This is what your JRE is expecting.
Java SE 15 = 59 (0x3B hex),
Java SE 14 = 58 (0x3A hex),
Java SE 13 = 57 (0x39 hex),
Java SE 12 = 56 (0x38 hex),
Java SE 11 = 55 (0x37 hex),
Java SE 10 = 54 (0x36 hex),[[4]](https://en.wikipedia.org/wiki/Java_class_file#cite_note-4)
Java SE 9 = 53 (0x35 hex),[[5]](https://en.wikipedia.org/wiki/Java_class_file#cite_note-5)
Java SE 8 = 52 (0x34 hex),
Java SE 7 = 51 (0x33 hex),
Java SE 6.0 = 50 (0x32 hex),
Java SE 5.0 = 49 (0x31 hex),
JDK 1.4 = 48 (0x30 hex),
JDK 1.3 = 47 (0x2F hex),
JDK 1.2 = 46 (0x2E hex),
JDK 1.1 = 45 (0x2D hex).

If you start IDEA from a command line, the console output should tell you the version and location of the JRE it's running on.  (At least it used to.)

**Comment by EricBishton** [comment]
@m0rkeulv, I don't think that the project settings will matter, since barisyild isn't compiling, but just running the plugin.

**Comment by barisyild** [comment]
> From https://en.wikipedia.org/wiki/Java_class_file#General_layout:
> 
> major version number of the class file format being used.[[3]](https://en.wikipedia.org/wiki/Java_class_file#cite_note-3) Java SE 21 = 65 (0x41 hex), Java SE 20 = 64 (0x40 hex), Java SE 19 = 63 (0x3F hex), Java SE 18 = 62 (0x3E hex), Java SE 17 = 61 (0x3D hex), <<<<<<-------- @barisyild, This is what is being complained about. Java SE 16 = 60 (0x3C hex), <<< --- This is what your JRE is expecting. Java SE 15 = 59 (0x3B hex), Java SE 14 = 58 (0x3A hex), Java SE 13 = 57 (0x39 hex), Java SE 12 = 56 (0x38 hex), Java SE 11 = 55 (0x37 hex), Java SE 10 = 54 (0x36 hex),[[4]](https://en.wikipedia.org/wiki/Java_class_file#cite_note-4) Java SE 9 = 53 (0x35 hex),[[5]](https://en.wikipedia.org/wiki/Java_class_file#cite_note-5) Java SE 8 = 52 (0x34 hex), Java SE 7 = 51 (0x33 hex), Java SE 6.0 = 50 (0x32 hex), Java SE 5.0 = 49 (0x31 hex), JDK 1.4 = 48 (0x30 hex), JDK 1.3 = 47 (0x2F hex), JDK 1.2 = 46 (0x2E hex), JDK 1.1 = 45 (0x2D hex).
> 
> If you start IDEA from a command line, the console output should tell you the version and location of the JRE it's running on. (At least it used to.)

Since each intellij uses its own embedded java version, 2023.1.3 version should be using java 16 on every device.

You can check from following image:
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/3c74aca1-1ded-45cd-a3fa-6f80c79a8036)

![image](https://github.com/HaxeFoundation/intellij-haxe/assets/25794892/c6411094-9542-4b99-9fc6-ebaf8ac8378d)

**Comment by barisyild** [comment]
By the way, an important note, the plugin works quite well, only this error occurs during the build.

Maybe the only compilation related class was compiled with high java version? (Or dependency requires higher java version)

**Comment by EricBishton** [comment]
> By the way, an important note, the plugin works quite well, only this error occurs during the build.

My mistake, you _are_ building.  So @m0rkeulv is probably right about the project settings you have locally.

**Comment by barisyild** [comment]
> 

Problem solved @m0rkeulv is right

**Comment by barisyild** [comment]
> > By the way, an important note, the plugin works quite well, only this error occurs during the build.
> 
> My mistake, you _are_ building. So @m0rkeulv is probably right about the project settings you have locally.

Thank you for your precious time

**Comment by EricBishton** [comment]
> Thank you for your precious time

Any time.  :)
