### ISSUE TITLE
Exception in plugin Haxe Toolkit Support (1.4.21)

### ISSUE THREAD

**Issue by cbricken** [HaxeFoundation/intellij-haxe#1143]
Using IntelliJ 2023.3.2 Ultimate Edition, Haxe 4.2.5. Errors displayed soon after launching IDE, apparently during indexing. 
This only displayed once, while trying to resolve a persistent issue where indexing never completes (we have a pretty large codebase, thousands of files).

[stacktrace.txt](https://github.com/HaxeFoundation/intellij-haxe/files/13814564/stacktrace.txt)

**Comment by m0rkeulv** [comment]
it happens due to missing SDK (cant find the class/file for `Function`), ill add a check so that  wont log it as an error and return unknown instead. There could probably be other similar cases for other types  that are defined in the SDK and expected by the plugin . (Array and Map most likely)

**Comment by cbricken** [comment]
Here's another IDE Internal Error:

com.intellij.diagnostic.PluginException: Intention Description Dir URL is null: Replace with single class imports; ReplaceImportStatementWithWildcardWithSingleClassImports; while looking for description.html [Plugin: com.intellij.plugins.haxe]
	at com.intellij.codeInsight.intention.impl.config.IntentionActionMetaData.getResourceLocation(IntentionActionMetaData.java:62)
	at com.intellij.codeInsight.intention.impl.config.BeforeAfterActionMetaData.getDescription(BeforeAfterActionMetaData.java:132)
	at com.intellij.codeInsight.intention.impl.config.IntentionManagerSettings$IntentionSearchableOptionContributor.processOptions(IntentionManagerSettings.kt:85)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.lambda$initialize$0(SearchableOptionsRegistrarImpl.java:137)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.kt:34)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:50)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.initialize(SearchableOptionsRegistrarImpl.java:137)
	at com.intellij.ide.ui.search.SearchableOptionsRegistrarImpl.getAcceptableDescriptions(SearchableOptionsRegistrarImpl.java:458)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$optionsFlow$1.invokeSuspend(ActionAsyncProvider.kt:297)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$optionsFlow$1.invoke(ActionAsyncProvider.kt)
	at com.intellij.ide.util.gotoByName.ActionAsyncProvider$optionsFlow$1.invoke(ActionAsyncProvider.kt)
	at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo$suspendImpl(Builders.kt:320)
	at kotlinx.coroutines.flow.ChannelFlowBuilder.collectTo(Builders.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by m0rkeulv** [comment]
Do you know what you did when this occurred ? i am not sure how to reproduce it.

**Comment by cbricken** [comment]
Unfortunately it’s not consistent. Just happened on startup once or twice.
I was hoping the stack trace would be illuminating. But sometimes it’s just a mystery.
Thanks for working on the plugin!
