### ISSUE TITLE
Assertion failure during Semantic Annotation.

### ISSUE THREAD

**Issue by EBatTiVo** [HaxeFoundation/intellij-haxe#316]
When annotating code, sometimes a reference does not have an identifier.  However, the HaxeReferenceExpressionImpl class has the getIdentifier function marked with a NotNull annotation, and calls findNotNullChildByClass() which throws an error when the entity does not exist.

The solution is to remove the NotNull annotation and call findChildByClass().  There are also two usages of that function that need to be verified.  TypeChecker.check() and HaxeResolver.resolve().

This code generates the following PSI:

``` haxe
        var bo = new haxe.io.BytesOutput();
```

```
          LOCAL_VAR_DECLARATION 'var bo = new haxe.io.BytesOutput();'(85932,85967)
            PsiJavaToken:var('var')(85932,85935)
            PsiWhiteSpace(' ')(85935,85936)
            LOCAL_VAR_DECLARATION_PART 'bo'(85936,85966)
              COMPONENT_NAME 'bo'(85936,85938)
                IDENTIFIER (85936,85938)
                  PsiJavaToken:ID('bo')(85936,85938)
              PsiWhiteSpace(' ')(85938,85939)
              VAR_INIT (85939,85966)
                PsiJavaToken:=('=')(85939,85940)
                PsiWhiteSpace(' ')(85940,85941)
                NEW_EXPRESSION :new haxe.io.BytesOutput():HaxeNewExpressionImpl(85941,85966)
                  PsiJavaToken:new('new')(85941,85944)
                  PsiWhiteSpace(' ')(85944,85945)
                  TYPE (85945,85964)
                    REFERENCE_EXPRESSION :haxe.io.BytesOutput:HaxeReferenceExpressionImpl(85945,85964)
                      REFERENCE_EXPRESSION :haxe.io:HaxeReferenceExpressionImpl(85945,85952)
                        REFERENCE_EXPRESSION :haxe:HaxeReferenceExpressionImpl(85945,85949)
                          IDENTIFIER (85945,85949)
                            PsiJavaToken:ID('haxe')(85945,85949)
                        PsiJavaToken:.('.')(85949,85950)
                        REFERENCE_EXPRESSION :io:HaxeReferenceExpressionImpl(85950,85952)
                          IDENTIFIER (85950,85952)
                            PsiJavaToken:ID('io')(85950,85952)
                      PsiJavaToken:.('.')(85952,85953)
                      REFERENCE_EXPRESSION :BytesOutput:HaxeReferenceExpressionImpl(85953,85964)
                        IDENTIFIER (85953,85964)
                          PsiJavaToken:ID('BytesOutput')(85953,85964)
                  PsiJavaToken:(('(')(85964,85965)
                  PsiJavaToken:)(')')(85965,85966)
            PsiJavaToken:;(';')(85966,85967)
```

The partial stack is:

```
 [30253974]  ERROR - n.impl.GeneralHighlightingPass - IntelliJ IDEA (Cardea) IU-135.1286  Build #IU-135.1286 
[30253974]  ERROR - n.impl.GeneralHighlightingPass - JDK: 1.6.0_41 
[30253974]  ERROR - n.impl.GeneralHighlightingPass - VM: Java HotSpot(TM) Server VM 
[30253974]  ERROR - n.impl.GeneralHighlightingPass - Vendor: Sun Microsystems Inc. 
[30253974]  ERROR - n.impl.GeneralHighlightingPass - OS: Linux 
[30253974]  ERROR - n.impl.GeneralHighlightingPass - Last Action: Find 
[30254287]  ERROR - tellij.psi.impl.PsiElementBase - haxe.io.BytesOutput
parent=haxe.io.BytesOutput 
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:113)
    at com.intellij.psi.impl.PsiElementBase.notNullChild(PsiElementBase.java:282)
    at com.intellij.psi.impl.PsiElementBase.findNotNullChildByClass(PsiElementBase.java:306)
    at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceExpressionImpl.getIdentifier(HaxeReferenceExpressionImpl.java:45)
    at com.intellij.plugins.haxe.ide.annotator.TypeChecker.check(HaxeSemanticAnnotator.java:168)
    at com.intellij.plugins.haxe.ide.annotator.HaxeSemanticAnnotator.analyzeSingle(HaxeSemanticAnnotator.java:52)
    at com.intellij.plugins.haxe.ide.annotator.HaxeSemanticAnnotator.annotate(HaxeSemanticAnnotator.java:41)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:160)
    at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
    at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$5.run(GeneralHighlightingPass.java:312)
```

TIR: STB-11118

**Comment by EBatTiVo** [comment]
A hack which works around the issue is in PR #324.  Even if we take that, a proper fix for this requires a BNF fix, because HaxeReferenceExpression is a generated class.

**Comment by EBatTiVo** [comment]
Hack has been merged.  Still have work to fix this correctly.

**Comment by EricBishton** [comment]
Somewhere along the line, this was fixed both in code (the SemanticAnnotator deals with nulls from this method correctly) and in the BNF (nothing extends referenceExpression that doesn't have an identifier).
