### ISSUE TITLE
Haxe plugin version "0.9.7 for IDEA 14.1.4" is not compatible with AppCode / PyCharm / WebStorm / IntelliJ IDEA (143.1184)

### ISSUE THREAD

**Issue by nicity** [HaxeFoundation/intellij-haxe#378]
Following exceptions are present in logs (taken from https://youtrack.jetbrains.com/issue/HAXE-385)
2015-12-15 18:01:20,715 [  11888]  ERROR - psi.SingleRootFileViewProvider - com/intellij/psi/PsiModifierListOwner 
java.lang.NoClassDefFoundError: com/intellij/psi/PsiModifierListOwner
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:257)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:253)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:222)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:257)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:253)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:222)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.intellij.plugins.haxe.lang.parser.HaxeParserDefinition.createFile(HaxeParserDefinition.java:71)
    at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:410)
    at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:351)
    at com.intellij.psi.SingleRootFileViewProvider.b(SingleRootFileViewProvider.java:329)
    at com.intellij.psi.SingleRootFileViewProvider.getPsiInner(SingleRootFileViewProvider.java:174)
    at com.intellij.psi.SingleRootFileViewProvider.getPsi(SingleRootFileViewProvider.java:158)
    at com.intellij.psi.impl.PsiFileFactoryImpl.trySetupPsiForFile(PsiFileFactoryImpl.java:121)
    at com.intellij.psi.impl.PsiFileFactoryImpl.createFileFromText(PsiFileFactoryImpl.java:85)
    at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:100)
    at com.intellij.util.indexing.FileContentImpl.getPsiFile(FileContentImpl.java:75)
    at com.intellij.plugins.haxe.ide.index.HaxeComponentIndex$MyDataIndexer.map(HaxeComponentIndex.java:125)
    at com.intellij.plugins.haxe.ide.index.HaxeComponentIndex$MyDataIndexer.map(HaxeComponentIndex.java:121)
    at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1744)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1671)
    at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1616)
    at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:109)
    at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:225)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:245)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:239)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.PsiModifierListOwner PluginClassLoader[com.intellij.plugins.haxe, 0.9.7 for IDEA 14.1.4]
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 55 more
2015-12-15 18:01:20,720 [  11893]  ERROR - psi.SingleRootFileViewProvider - AppCode 3.3.2  Build #OC-143.1184.23 
2015-12-15 18:01:20,720 [  11893]  ERROR - psi.SingleRootFileViewProvider - JDK: 1.8.0_40-release 
2015-12-15 18:01:20,720 [  11893]  ERROR - psi.SingleRootFileViewProvider - VM: OpenJDK 64-Bit Server VM 
2015-12-15 18:01:20,720 [  11893]  ERROR - psi.SingleRootFileViewProvider - Vendor: JetBrains s.r.o 
2015-12-15 18:01:20,720 [  11893]  ERROR - psi.SingleRootFileViewProvider - OS: Mac OS X 
2015-12-15 18:01:20,721 [  11894]  ERROR - psi.SingleRootFileViewProvider - Last Action:  
2015-12-15 18:01:20,724 [  11897]  ERROR - napi.project.CacheUpdateRunner - Error while indexing /Users/jetbrains/Documents/tvOS_objc_app/tvOS_objc_app/textHaxe.hx
To reindex this file IDEA has to be restarted 
java.lang.NullPointerException
    at com.intellij.util.indexing.FileContentImpl.getPsiFile(FileContentImpl.java:76)
    at com.intellij.plugins.haxe.ide.index.HaxeComponentIndex$MyDataIndexer.map(HaxeComponentIndex.java:125)
    at com.intellij.plugins.haxe.ide.index.HaxeComponentIndex$MyDataIndexer.map(HaxeComponentIndex.java:121)
    at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1744)
    at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1671)
    at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1616)
    at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:109)
    at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:225)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:245)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:239)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

**Comment by nicity** [comment]
It looks like plugin depends on Java language implementation (PsiModifierListOwner) and does not state the dependency in plugin.xml, alternatively one can try to avoid using java support specific classes for ability to use plugin in AppCode / WebStorm for example

**Comment by nicity** [comment]
Also relevant issue from JetBrains issue tracker https://youtrack.jetbrains.com/issue/HAXE-381

2015-12-15 19:07:45,165 [  35457]  ERROR - aemon.impl.PassExecutorService - com/intellij/psi/PsiJavaCodeReferenceElement 
java.lang.NoClassDefFoundError: com/intellij/psi/PsiJavaCodeReferenceElement
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:257)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:253)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:222)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:257)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:253)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:222)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:257)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:253)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:222)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.intellij.plugins.haxe.lang.RegexLanguageInjector.getLanguagesToInject(RegexLanguageInjector.java:34)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl$PsiManagerRegisteredInjectorsAdapter.getLanguagesToInject(InjectedLanguageManagerImpl.java:515)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider$MyInjProcessor.process(InjectedPsiCachedValueProvider.java:82)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:474)
	at com.intellij.psi.impl.source.tree.injected.InjectedPsiCachedValueProvider.doCompute(InjectedPsiCachedValueProvider.java:62)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.a(InjectedLanguageUtil.java:316)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:145)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass$2.process(LineMarkersPass.java:210)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass$2.process(LineMarkersPass.java:207)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInjectableElements(InjectedLanguageManagerImpl.java:233)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.collectLineMarkersForInjected(LineMarkersPass.java:207)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:113)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.PsiJavaCodeReferenceElement PluginClassLoader[com.intellij.plugins.haxe, 0.9.7 for IDEA 14.1.4]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 57 more
2015-12-15 19:07:45,167 [  35459]  ERROR - aemon.impl.PassExecutorService - AppCode 3.3.2  Build #OC-143.1184.23 
2015-12-15 19:07:45,167 [  35459]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_40-release 
2015-12-15 19:07:45,167 [  35459]  ERROR - aemon.impl.PassExecutorService - VM: OpenJDK 64-Bit Server VM 
2015-12-15 19:07:45,167 [  35459]  ERROR - aemon.impl.PassExecutorService - Vendor: JetBrains s.r.o 
2015-12-15 19:07:45,167 [  35459]  ERROR - aemon.impl.PassExecutorService - OS: Mac OS X 
2015-12-15 19:07:45,167 [  35459]  ERROR - aemon.impl.PassExecutorService - Last Action:

**Comment by daniel-v** [comment]
I am getting this error for Webstorm as well.

**Comment by nicity** [comment]
https://youtrack.jetbrains.com/issue/IDEA-149681

2015-12-22 14:43:40,174 [ 60484] ERROR - llij.ide.plugins.PluginManager - NATIVE_MAC_CHOOSER_SHOW_HIDDEN_FILES

java.lang.NoSuchFieldError: NATIVE_MAC_CHOOSER_SHOW_HIDDEN_FILES
 at com.intellij.plugins.haxe.config.sdk.HaxeSdkType.getHomeChooserDescriptor(HaxeSdkType.java:120)
 at com.intellij.openapi.projectRoots.impl.SdkConfigurationUtil.selectSdkHome(SdkConfigurationUtil.java:278)
 at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel.doAdd(ProjectSdksModel.java:273)
 at com.intellij.openapi.roots.ui.configuration.projectRoot.ProjectSdksModel$3.actionPerformed(ProjectSdksModel.java:255)
 at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:856)
 at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:842)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
2015-12-22 14:43:40,175 [ 60485] ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 15.0.2 Build #IU-143.1184.17
2015-12-22 14:43:40,175 [ 60485] ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_40-release
2015-12-22 14:43:40,175 [ 60485] ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM
2015-12-22 14:43:40,176 [ 60486] ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o
2015-12-22 14:43:40,176 [ 60486] ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X

**Comment by EBatTiVo** [comment]
This occurs because the intellij-haxe plugin has dependency upon portions of the Java support in IDEA that has been removed from those products.  (IIRC, all of the functionality of specialized products is available  in IDEA through plugins.  So the workaround is to move to IDEA.)

Fixing this is going to be non-trivial.  We (TiVo engineers) made a conscious decision to depend upon and use the Java implementation to get full PSI support for Haxe in the plugin.  And we added a LOT of code that does so.

**Comment by nicity** [comment]
@EBatTiVo There is simple fix for plugin not to be compatible with WebStorm / AppCode / PyCharm

**Comment by EBatTiVo** [comment]
I'm not sure how to mark the plugin as not compatible with other products.  I know how to limit it based upon code line and version.

BTW, I looked at the tile again and noticed that IDEA is listed.  None of the 14.x builds are compatible with the IDEA 15 (143.xxx code line).  The 0.9.8 plugins are marked correctly for that now.  We don't limit the   maximum build until we *know* there's an incompatibility.  That way folks can try it on new releases (particularly EAP) if they want, knowing that there are likely issues.

When I get a clean ant build of v15, I'll be making a new release.

**Comment by Ramblurr** [comment]
Got here because I just installed the Haxe Support plugin in the latest 2016.2.4 IntelliJ IDEA Ultimate edition.

Is this plugin not compatible with IDEA?

**Comment by EBatTiVo** [comment]
@Ramblurr The plugin is compatible with IDEA.  The currently published versions do not work with 2016.x versions; the 0.10.1-rc2 candidate does: https://github.com/TiVo/intellij-haxe/releases/tag/0.10.1-rc2.  Instructions for installing from github releases are here: https://github.com/TiVo/intellij-haxe#to-manually-install-the-latest-or-a-previous-github-release.

**Comment by Ramblurr** [comment]
Superb, thanks @EBatTiVo

**Comment by Blake-R** [comment]
Still got exception on Psi at PyCharm 2016.3.2 and Haxe plugin 0.10.1.1.

`
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.PsiField PluginClassLoader[com.intellij.plugins.haxe, 0.10.1.1 for IDEA 2016.1 through 2016.3.2]
`

After that PyCharm do not shows any files in project..

[Haxe plugin exception full log](https://gist.github.com/Blake-R/8efb537c1b2057bbb12863687894b296)

**Comment by EricBishton** [comment]
@Blake-R PyCharm does not include the Java language PSI classes that IDEA does and that Haxe relies upon.  Placing the jar from the community edition of IDEA on the classpath when you start PyCharm may allow the plugin to work correctly for you, but it's not a supported configuration and may lead to other issues.

**Comment by Blake-R** [comment]
@EricBishton I'll try. What kind of .jar I need? Something a-la "psi.jar"? :)

**Comment by EricBishton** [comment]
@Blake-R When I was trying to get the plugin working with AppCode on a Mac, it was idea.jar that was missing.  The way to tell for sure is to look in the jar manifests for the class(es) you are missing.

Of course, the easiest and most consistent thing is to open Haxe projects using IDEA Community Edition, which is free, and can load all of the same plugins that PyCharm has.

**Comment by EricBishton** [comment]
With the advent of 2019.3(?) versions of IDEA now publishing Java as a separate plugin, and us subsequently declaring our dependency on it (in the plugin.xml), this issue is solved for all newer versions.
