### ISSUE TITLE
HaxelibManager attempts to do something when creating a Java project

### ISSUE THREAD

**Issue by as3boyan** [HaxeFoundation/intellij-haxe#397]
HaxelibManager attempts to do something when creating a Java project

```
Connected to the target VM, address: '127.0.0.1:60601', transport: 'socket'
лют 01, 2016 8:27:47 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[   4552]   WARN - om.intellij.util.ProfilingUtil - Profiling agent is not enabled. Add -agentlib:yjpagent to idea.vmoptions if necessary to profile IDEA. 
[   6936]   WARN - .ExternalResourceManagerExImpl - Cannot find standard resource. filename:/META-INF/tapestry_5_3.xsd class=class com.intellij.javaee.ResourceRegistrarImpl, classLoader:null 
java.io.IOException: Cannot run program "haxelib": CreateProcess error=2, ?? ??????? ????? ????????? ????
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at com.intellij.plugins.haxe.haxelib.HaxelibCommandUtils.getProcessStdout(HaxelibCommandUtils.java:150)
    at com.intellij.plugins.haxe.haxelib.HaxelibCommandUtils.getProcessStdout(HaxelibCommandUtils.java:237)
    at com.intellij.plugins.haxe.haxelib.HaxelibCommandUtils.issueHaxelibCommand(HaxelibCommandUtils.java:96)
    at com.intellij.plugins.haxe.haxelib.HaxelibLibraryCache.<init>(HaxelibLibraryCache.java:62)
    at com.intellij.plugins.haxe.haxelib.HaxelibLibraryCacheManager$SdkEntry.<init>(HaxelibLibraryCacheManager.java:101)
    at com.intellij.plugins.haxe.haxelib.HaxelibLibraryCacheManager.getLibraryCache(HaxelibLibraryCacheManager.java:86)
    at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.syncProjectClasspath(HaxelibProjectUpdater.java:585)
    at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.synchronizeClasspaths(HaxelibProjectUpdater.java:546)
    at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.access$300(HaxelibProjectUpdater.java:83)
    at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$ProjectUpdateQueue.doUpdateWork(HaxelibProjectUpdater.java:1257)
    at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$ProjectUpdateQueue.access$200(HaxelibProjectUpdater.java:1098)
    at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$ProjectUpdateQueue$3$1.run(HaxelibProjectUpdater.java:1239)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.io.IOException: CreateProcess error=2, ?? ??????? ????? ????????? ????
    at java.lang.ProcessImpl.create(Native Method)
    at java.lang.ProcessImpl.<init>(ProcessImpl.java:385)
    at java.lang.ProcessImpl.start(ProcessImpl.java:136)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
    ... 26 more
```

**Comment by as3boyan** [comment]
I am working on it

**Comment by as3boyan** [comment]
Fixed.

**Comment by as3boyan** [comment]
To reproduce, create sample Java project
