### ISSUE TITLE
EditorPreviousWordWithSelection: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by hoha** [HaxeFoundation/intellij-haxe#652]
Haxe Support 0.11.0 for IDEA 2016.1 through 2017.x
IntelliJ IDEA 172.3544
Windows 10
JetBrains s.r.o 1.8.0_152-release 

extracted from an automatic report 

~~~~
<< Index: 0, Size: 0

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.remove(ArrayList.java:492)
	at com.intellij.plugins.haxe.model.HaxeMethodModel.getParametersWithContext(HaxeMethodModel.java:77)
	at com.intellij.plugins.haxe.model.HaxeMethodModel.getPresentableText(HaxeMethodModel.java:129)
	at com.intellij.plugins.haxe.ide.HaxeLookupElement.renderElement(HaxeLookupElement.java:93)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.renderItemApproximately(LookupImpl.java:453)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(LookupImpl.java:245)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItemToLookup(CompletionProgressIndicator.java:459)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItem(CompletionProgressIndicator.java:450)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.lambda$consume$0(CompletionThreading.java:158)
	at com.intellij.codeInsight.completion.AsyncCompletion$1WeighItems.run(CompletionThreading.java:126)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:108)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:939)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

~~~~

**Comment by EricBishton** [comment]
The method getParametersWithContext is not checking the number of parameters before removing the first one.  Without looking too closely (yet), I believe that this method is being used to detect static extensions, and the return value of isExtension() is true.  In this case, there should always be more than one parameter.  So, while I can just code around this error, it would just hide the underlying cause (isExtension() returning true when it shouldn't).

@hoha - Please add a minimal reproducible example (code you are editing) and steps to reproduce.  Thanks.

**Comment by mayakwd** [comment]
Steps to reproduce:
```
package ;
using StaticExt;
class Test {
    public function new() {
        var a:String = "";
        a.n|;
    }
}
```
```
package ;

class StaticExt {
    public static function name():String {

    }
}
```

**Comment by mayakwd** [comment]
This could be closed too

**Comment by EricBishton** [comment]
Will be in release 0.11.2.
