### ISSUE TITLE
Unexpected PSI format when looking up an 'extends' identifier with package name. (Throws exception)

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#674]
Parsing this from haxelib/Main.hx:
```haxe
class SiteProxy extends haxe.remoting.Proxy<haxelib.SiteApi> {
}
```
The plugin is looking up the identifier for the extends list and expecting to find it at the second level.  Since this is a reference using dotted notation, the target is actually a reference at that point.

```
INHERIT_LIST "extends haxe.remoting.Proxy<haxelib.SiteApi>"
  EXTENDS_DECLARATION "extends haxe.remoting.Proxy<haxelib.SiteApi>"
    HaxePsiToken:extends "extends"
    PsiWhiteSpace
    TYPE "haxe.remoting.Proxy<haxelib.SiteApi>"
      REFERENCE_EXPRESSION "haxe.remoting.Proxy":haxe.remoting.Proxy:HaxeReferenceExpressionImpl
        REFERENCE_EXPRESSION "haxe.remoting":haxe.remoting:HaxeReferenceExpressionImpl
          REFERENCE_EXPRESSION "haxe":haxe:HaxeReferenceExpressionImpl
            IDENTIFIER "haxe"
              HaxePsiToken:ID "haxe"
```

Stack Dump:
```
2017-09-26 17:41:34,266 [ 769869]  ERROR - aemon.impl.PassExecutorService - Missing required child of type com.intellij.plugins.haxe.lang.psi.HaxeIdentifier 
java.lang.AssertionError: Missing required child of type com.intellij.plugins.haxe.lang.psi.HaxeIdentifier
	at com.intellij.psi.util.PsiTreeUtil.getRequiredChildOfType(PsiTreeUtil.java:361)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeTypeListPartPsiMixinImpl$HaxeClassDelegateForTypeChild.getNameIdentifier(HaxeTypeListPartPsiMixinImpl.java:544)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeTypeListPartPsiMixinImpl.getNameIdentifier(HaxeTypeListPartPsiMixinImpl.java:256)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeTypeListPartPsiMixinImpl.getNameIdentifier(HaxeTypeListPartPsiMixinImpl.java:45)
	at com.intellij.codeInspection.NonAsciiCharactersInspection$1.visitElement(NonAsciiCharactersInspection.java:82)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeTypeOrAnonymousImpl.accept(HaxeTypeOrAnonymousImpl.java:21)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:70)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:282)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:250)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1160)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:249)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
2017-09-26 17:41:34,266 [ 769869]  ERROR - aemon.impl.PassExecutorService - IntelliJ IDEA 2017.2.4  Build #IU-172.4155.36 
2017-09-26 17:41:34,266 [ 769869]  ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_131 
2017-09-26 17:41:34,266 [ 769869]  ERROR - aemon.impl.PassExecutorService - VM: Java HotSpot(TM) 64-Bit Server VM 
2017-09-26 17:41:34,266 [ 769869]  ERROR - aemon.impl.PassExecutorService - Vendor: Oracle Corporation 
2017-09-26 17:41:34,266 [ 769869]  ERROR - aemon.impl.PassExecutorService - OS: Windows 10 
2017-09-26 17:41:34,266 [ 769869]  ERROR - aemon.impl.PassExecutorService - Last Action: PsiViewerForContext 
```

Using IDEA 2107.2.4, plugin 0.11.1+, master branch at e22e9a33

**Comment by mayakwd** [comment]
Extended sample
```haxe
package issue674;
class TestCase {
    public function new() {
        var variable1:haxe.ds.ObjectMap<haxe.Int32, haxe.Int64>;
        var variable2 = new haxe.remoting.Proxy<haxe.Int32>();
    }
}

class SiteProxy extends haxe.remoting.Proxy<haxe.Int32> {
}
```

**Comment by mayakwd** [comment]
This could be closed

**Comment by EricBishton** [comment]
Verified.  Fixed with https://github.com/HaxeFoundation/intellij-haxe/commit/37d1b0b0adcc5733c9588975627a00ac7bf277c9
