### ISSUE TITLE
[PhpStorm] "Could not initialize class com.intellij.plugins.haxe.lang.lexer.HaxeTokenTypes" at launch causing some bugs

### ISSUE THREAD

**Issue by afourmeaux** [HaxeFoundation/intellij-haxe#680]
- Plugin version : 0.11.1
- IDEA version : PhpStorm 2017.2.4 / 2017.2.3 EAP
- OS and OS version : Linux Ubuntu GNOME 17.04
- JDK version : openjdk 1.8.0_131

Hi, 
I installed your plugin on PhpStorm and tested on the 2017.2.4 and 2017.2.3 EAP version and now some things bug due to an error appearing at the launch "Could not initialize class com.intellij.plugins.haxe.lang.lexer.HaxeTokenTypes" and i think because of that i have this error "Fatal error initializing 'com.intellij.psi.stubs.StubUpdatingIndex'" that make "Navigate | Declaration", "Edit | Extend Selection" and the Project tree not working. I also can't open .hx files but i can open the .hxml. And maybe other things but that the ones i noted. And i'm sur it come from this plugin because when i deactivate it everything is back to normal. In parallel i have IntelliJ 2017.2.5 installed with your plugin and it work like a charm.

**Comment by Sjeiti** [comment]
This bug persists for 'v1.2 for IDEA 2018.x' and PHPStorm 2018.1.6 (and 2018.1.7)
Same issue: plugin error makes IDE unusable.

Here's the full trace:
```
Could not initialize class com.intellij.plugins.haxe.lang.lexer.HaxeTokenTypes
java.lang.NoClassDefFoundError: Could not initialize class com.intellij.plugins.haxe.lang.lexer.HaxeTokenTypes
	at com.intellij.plugins.haxe.ide.completion.HaxeControllingCompletionContributor.<init>(HaxeControllingCompletionContributor.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:75)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
	at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
	at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
	at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
	at com.intellij.codeInsight.completion.CompletionPreloader.preload(CompletionPreloader.java:32)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.application.Preloader.a(Preloader.java:72)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
