### ISSUE TITLE
NPE at SpecificHaxeClassReference.toStringWithConstant in IDEA 173.4301 

### ISSUE THREAD

**Issue by chrkv** [HaxeFoundation/intellij-haxe#720]
Plugin version `0.11.2 for IDEA 2017.x`
```
java.lang.NullPointerException
	at com.intellij.plugins.haxe.model.type.SpecificHaxeClassReference.toStringWithConstant(SpecificHaxeClassReference.java:125)
	at com.intellij.plugins.haxe.model.type.SpecificHaxeClassReference.toString(SpecificHaxeClassReference.java:144)
	at com.intellij.plugins.haxe.model.type.ResultHolder.toString(ResultHolder.java:102)
	at com.intellij.plugins.haxe.lang.psi.impl.AbstractHaxeNamedComponent$1.getPresentableText(AbstractHaxeNamedComponent.java:127)
	at com.intellij.plugins.haxe.ide.HaxeLookupElement.renderElement(HaxeLookupElement.java:87)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.renderItemApproximately(LookupImpl.java:453)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.addItem(LookupImpl.java:245)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItemToLookup(CompletionProgressIndicator.java:459)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.addItem(CompletionProgressIndicator.java:450)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.lambda$null$0(CompletionThreading.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:181)
	at com.intellij.codeInsight.completion.AsyncCompletion$1.lambda$consume$1(CompletionThreading.java:157)
	at com.intellij.codeInsight.completion.AsyncCompletion$1WeighItems.run(CompletionThreading.java:125)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:108)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:104)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by EricBishton** [comment]
Got any specific code that triggers this?

**Comment by mayakwd** [comment]
I've fixed it already somewhere in the code of current or planned pull-request. I'll check it.
