### ISSUE TITLE
NPE from the IntelliJ's Exception Tracker

### ISSUE THREAD

**Issue by ignatov** [HaxeFoundation/intellij-haxe#814]
<< java.lang.NullPointerException
	at com.intellij.plugins.haxe.haxelib.HaxelibUtil.getLibraryRoot(HaxelibUtil.java:89)
	at com.intellij.plugins.haxe.haxelib.HaxeLibrary.load(HaxeLibrary.java:188)
	at com.intellij.plugins.haxe.haxelib.HaxelibLibraryCache.<init>(HaxelibLibraryCache.java:60)
	at com.intellij.plugins.haxe.haxelib.HaxelibLibraryCacheManager$SdkEntry.<init>(HaxelibLibraryCacheManager.java:101)
	at com.intellij.plugins.haxe.haxelib.HaxelibLibraryCacheManager.getLibraryCache(HaxelibLibraryCacheManager.java:86)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.getLibraryCache(HaxelibProjectUpdater.java:215)
	at com.intellij.plugins.haxe.haxelib.HaxeLibraryReference.create(HaxeLibraryReference.java:77)
	at com.intellij.plugins.haxe.haxelib.HaxelibUtil.getProjectLibraries(HaxelibUtil.java:260)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.syncProjectClasspath(HaxelibProjectUpdater.java:906)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.synchronizeClasspaths(HaxelibProjectUpdater.java:743)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.access$800(HaxelibProjectUpdater.java:84)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$ProjectUpdateQueue.doUpdateWork(HaxelibProjectUpdater.java:1567)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$ProjectUpdateQueue.access$700(HaxelibProjectUpdater.java:1408)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$ProjectUpdateQueue$3$1.run(HaxelibProjectUpdater.java:1549)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mayakwd** [comment]
@ignatov, please provide plugin version.

**Comment by ignatov** [comment]
Have no idea about the plugin version, the report is from the internal exception analyzer, reported by a plugin user.
