### ISSUE TITLE
IDE Fatal Error - StackOverflowError

### ISSUE THREAD

**Issue by RedHead90** [HaxeFoundation/intellij-haxe#898]
Haxe 3.4.7
Haxe Toolkit Support 1.1.dev.1b1a9b3 for IDEA 2018.x (Dec 22, 2018)
Haxe Toolkit Support 1.1.dev.958249b for IDEA 2018.x (Dec 14, 2018)
IntelliJ IDEA 2018.1
Build #IU-181.4203.550, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

```
null
java.lang.StackOverflowError
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at java.lang.StringBuilder.<init>(StringBuilder.java:113)
	at com.intellij.plugins.haxe.model.type.SpecificHaxeClassReference.toStringWithoutConstant(SpecificHaxeClassReference.java:111)
	at com.intellij.plugins.haxe.model.type.ResultHolder.toStringWithoutConstant(ResultHolder.java:115)
	at com.intellij.plugins.haxe.model.type.SpecificHaxeClassReference.toStringWithoutConstant(SpecificHaxeClassReference.java:118)
...
	at com.intellij.plugins.haxe.model.type.ResultHolder.toStringWithoutConstant(ResultHolder.java:115)
	at com.intellij.plugins.haxe.model.type.SpecificHaxeClassReference.toStringWithoutConstant(SpecificHaxeClassReference.java:118)
```

**Comment by EricBishton** [comment]
@RedHead90 

I suppose this is using code that is self-referential?  (e.g. there is an illegal cycle in the inheritance chain)
Can you please provide a minimal sample that causes this behavior?  Thanks!

**Comment by EricBishton** [comment]
Actually, this is in code that is trying to generate parameter arguments to a string.  For example, `myclass<sometype>` and for some reason is continuously resolving to itself.  So, `sometype` is being expanded as `<sometype<sometype<sometype...`.  We might need an exclusion guard, but there may be something more basic going on here.  An example will be a huge help.

**Comment by RedHead90** [comment]
Sorry, but I could not reproduce this problem in the minimal example. The archive I attached contains the "Tree" module. When I enter it for editing, an IDE error occurs. The module itself contains some logical errors, but compiles without errors. Package "eventu" I threw off just to save links. The classes in it do not cause IDE errors when I open them.

[tree.zip](https://github.com/HaxeFoundation/intellij-haxe/files/2705468/tree.zip)

**Comment by EricBishton** [comment]
OK. Thanks.  I will take a look.

**Comment by m0rkeulv** [comment]
Downloaded and opened all files for editing, no  `StackOverflowError`, probably solved in one of the latest versions. closing this one
