### ISSUE TITLE
Exception Argument for @NotNull parameter 'name' of com/intellij/plugins/haxe/haxelib/HaxeLibraryReference.create must not be null

### ISSUE THREAD

**Issue by CanIGetaPR** [HaxeFoundation/intellij-haxe#949]
Plugin Version: 1.2 for 2019.x
IJ: 2019.2
OS: Windows 64 bit
Occurrence: On project load
Stack Trace:

```
java.lang.RuntimeException: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'name' of com/intellij/plugins/haxe/haxelib/HaxeLibraryReference.create must not be null
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:175)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:638)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.doReadAction(HaxelibProjectUpdater.java:1044)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.syncModuleClasspaths(HaxelibProjectUpdater.java:702)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.synchronizeClasspaths(HaxelibProjectUpdater.java:744)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.access$800(HaxelibProjectUpdater.java:84)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$ProjectUpdateQueue.doUpdateWork(HaxelibProjectUpdater.java:1567)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$ProjectUpdateQueue.access$700(HaxelibProjectUpdater.java:1408)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$ProjectUpdateQueue$3$1.run(HaxelibProjectUpdater.java:1549)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'name' of com/intellij/plugins/haxe/haxelib/HaxeLibraryReference.create must not be null
	at com.intellij.plugins.haxe.haxelib.HaxeLibraryReference.$$$reportNull$$$0(HaxeLibraryReference.java)
	at com.intellij.plugins.haxe.haxelib.HaxeLibraryReference.create(HaxeLibraryReference.java)
	at com.intellij.plugins.haxe.haxelib.HaxeLibraryReference.matchesIdeaLib(HaxeLibraryReference.java:184)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.lookupLibrary(HaxelibProjectUpdater.java:262)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.lookupModelLibrary(HaxelibProjectUpdater.java:291)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.access$000(HaxelibProjectUpdater.java:84)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$2.processEntry(HaxelibProjectUpdater.java:344)
	at com.intellij.plugins.haxe.haxelib.HaxeLibraryList.iterate(HaxeLibraryList.java:269)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.addLibraries(HaxelibProjectUpdater.java:341)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.access$400(HaxelibProjectUpdater.java:84)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$4.run(HaxelibProjectUpdater.java:487)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:994)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$13.run(HaxelibProjectUpdater.java:1029)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:630)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.doWriteAction(HaxelibProjectUpdater.java:1026)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.updateModule(HaxelibProjectUpdater.java:460)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.resolveModuleLibraries(HaxelibProjectUpdater.java:247)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.syncOneModule(HaxelibProjectUpdater.java:674)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater.access$500(HaxelibProjectUpdater.java:84)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$5.run(HaxelibProjectUpdater.java:705)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:902)
	at com.intellij.plugins.haxe.haxelib.HaxelibProjectUpdater$14.run(HaxelibProjectUpdater.java:1047)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:312)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:152)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:433)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:817)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:766)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:405)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:404)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by CanIGetaPR** [comment]
Right, I need to figure out how to build from source so I can test the most up-to-date version.

**Comment by EricBishton** [comment]
Fixed with https://github.com/HaxeFoundation/intellij-haxe/commit/490e952b9c53d92920cf9b769cca1812275d02d8
